# NOTE: update this with your service name
service: startuplifers-tgbot-serverless

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-2
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  sampleEnvVar: ${env:SAMPLE_ENV_VAR}

functions:
  uploadTestApi:
    handler: uploadTestApi.main
    events:
      - http:
          method: get
  getStoredJobs:
    handler: getStoredJobs.main
    events:
      - http:
          method: get

  index:
    handler: index.main
    events:
      - http:
          method: get
